name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Run pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest
        pip install -r requirements.txt
        
    - name: Test with pytest
      run: pytest
